### ISSUE TITLE
AC analysis bug?

### ISSUE THREAD

**Issue by LdBeth** [Symbulator-Team/TI-89#2]
It seems this version has bug with AC as it cannot solve any circuit with inductor or capacitor, like `s\ac("e1,1,0,40:r1,1,2,3:l1,2,0,3",300)`. The "August 31 beta version" has been mentioned from the Facebook post but I do not know if anyone happens still having that version. Or if the changes were small I might able to patch it myself.

**Comment by LdBeth** [comment]
I find there is likely a typo in `s8`

where looks like:

```
If βtool="fd" or βtool="tr" Then
expr("solve((v"&αζ2&"-v"&αζ3&")/(s)=("&αζ4&")*(i"&αζ1&"-("&αζ5&")/s)+("&ζζ&"),i"&αζ1&")→eq"&αζ1)
Else
expr("solve((v"&αζ2&"-v"&αζ3&")/(ω*𝐢)=("&αζ4&")*(i"&αζ1&")+("&ζζ&"),i"&αζ1&")→eq"&αζ1)
EndIf
```

and the second `solve` should be `cSolve`, fixing that makes the example from Symbulator thesis paper:

```
s\ac("e1,1,0,(40∠-90°);r1,1,2,1.5E3;r2,2,3,1E3;l1,2,0,1/3; ca,3,0,(1/6)E-6",3000)
```

works again on this version of Symbulator.

**Comment by testfor-doom** [comment]
do you have the other versions of symbulator?

**Comment by LdBeth** [comment]
@testfor-doom there was a much older version "Q" available from internet archive of author's website

https://web.archive.org/web/20010419111945/http://sq.calc.org/

but if you mean the "latest version" then no, this repository is the latest version I could find.

**Comment by testfor-doom** [comment]
Thank you very much for the help, have a nice day

**Comment by LdBeth** [comment]
Close as it is fixed in main branch
